### PR TITLE
Input Log Submit Button Popup

### LINKED ISSUE #261: Seeding Input: popup when submit button is clicked
When the submit button is clicked on the seeding input, a seeding and planting log are created. Nothing happens on the user's side though. It makes it likely that the user will think nothing happened and click the submit button many times (making multiple of the same log).

To fix this, when the submit button is clicked a popup should appear letting the user go to the seeding report page or submit another log (if the user chooses this one, the inputs in the page should be reset).

To test this go to the Seedings Input subtab under FieldKit tab, which is on the home page.  

The code can be found by going to farmdata2_modules, then fd2_tabs, then fd2_field_kit, and in the seedingInput.html file.

Reference Issue: #263

### LINKED ISSUE #263: Cypress: test popup when submit button is clicked
There should be a cypress test(s), that tests whether a popup appears on the seeding input page when the submit button is clicked. The test(s) should test that it appears and that there are two options on the popup, one that takes you to the seeding report page and the other that resets the inputs on the seedings input page.

The code can be found by going to farmdata2_modules, then fd2_tabs, then fd2_field_kit, and in the seedingInput.spec.js file.

Run ./test_runner.bash e2e in the farmdata2_modules to run tests.

Reference issue: #261

### PR DESCRIPTION
**Pull request by IrisSC**
__Pull Request Description__

When the user clicked the submit button in the input seeding report page, logs would be created but nothing would happen on the user side. Now there is a popup that says they have submitted a log and it asks them if they would like to go to the seeding report page. If they click 'Ok' then it takes them to the seeding report page, otherwise it returns them to the page that they are on. There are no cypress tests for this yet. 

Closes #261 
Closes #263 

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

### CODE REVIEW

**Comment by braughtg** [comment]
Looks good.  Is it possible to cypress test that the pop up is shown and that it does to the correct location in each case depending upon what they click?

**Comment by braughtg** [comment]
Is this ready to go now?

**Comment by IrisSC** [comment]
Yes!

**Comment by braughtg** [comment]
I will test and merge this later today.

**Pull request merged**
