### PR TITLE
Labor report Subtab

### PR DESCRIPTION
**Pull request by astern21**
__Pull Request Description__

This is a Mockup of the LaborReport sub-tab. It is a complete copy of the SeedingReport subtab. 

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

### CODE REVIEW

**Comment by braughtg** [comment]
Looks like you are off to a good start here.  Your PR seems to delete the SeedingReport.spec.js file from the repository.  That file is not related to your PR but should not be removed from the FarmData2 repository as it contains test related to the Seeding Report page.

**Comment by astern21** [comment]
Need to figure out how to insert a Task column into the table without messing with data from other columns, because right now  the data in each column does not match its header.

**Comment by braughtg** [comment]
> Need to figure out how to insert a Task column into the table without messing with data from other columns, because right now the data in each column does not match its header.

You will need to insert a header for the new column into the arrays that are passed to the table.

**Comment by johnmaccormick** [comment]
It will be useful to note for future review purposes that this PR is based on work done in Prof John MacCormick's COMP 290 class at Dickinson College, Spring 2022.

**Comment by braughtg** [comment]
Closed as the course associated with this issue has concluded.  It will be preserved in the project history as a basis for implementation of this feature in the future.

**Pull request closed without merging**
