### PR TITLE
Updated comment

### PR DESCRIPTION
**Pull request by fiveminutes001**
__Pull Request Description__

<Add description>

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

### CODE REVIEW

**Comment by braughtg** [comment]
Your PR seems to have adjusted the formatting so that it appears that nearly every line in the file has been changed.  Please update the PR so that the changes are limited to only the line with the comment.

**Comment by fiveminutes001** [comment]
Sure. Worked with Visual Studio with Prettier. Not sure what happened, but
I’ll fix it.

בתאריך יום ב׳, 4 באוק׳ 2021 ב-20:10 מאת Grant Braught <
***@***.***>:

**Comment by braughtg** [comment]
I suspect that the formatting of our code is just different than what prettier did.  Better code formatting standards is on our to-do list.

**Comment by fiveminutes001** [comment]
After fixing this issue I’ll be happy to assist in that. Apart from being a
programmer in the last 6 years, I’m an agronomist and a water engineer by
the way.

בתאריך יום ב׳, 4 באוק׳ 2021 ב-20:42 מאת Grant Braught <
***@***.***>:

**Comment by braughtg** [comment]
Argronomist and programmer - thats not a common combination - but seems like an ideal fit for this type of project!  

Help with the code formatting guides would be great.  Check out Issue #79, it gives just a little information and is a place holder there so I didn't lose track of it.  If you want to further discuss code formatting we can do so there.

**Comment by braughtg** [comment]
Closes #287

**Pull request merged**
