### PR TITLE
Refactored dev/startup.bash Docker container

### LINKED ISSUE #655: Dev Container VNC Server is slow to start
When running `./fd2-up.bash` to start the development environment the `fd2_dev` container runs the VNC Server that is connected to in order to show the desktop environment.  It seems to take quite a while (20-30 seconds) after `./fd2-up.bash` reports that the Drupal cache has been cleared and that "FarmData2 started", before we can connect via VNC.  When you try to connect during this time, the VNC client just silently quits.

It would be good to be able to connect via VNC immediately after the "FarmData2 started" message.  It would be even better if the 20-30 second delay between clearing of the cache and connecting were eliminated.

This seems to have something to do with the dev container startup process.  Perhaps that can be streamlined or reordered?

### PR DESCRIPTION
**Pull request by WarpWing**
__Pull Request Description__

As part of my crusade to resolve #655, the actual dev container script is going to take some time to analyze but I figured I would start with the smallest fish and take a look at the actual startup script inside the dev container. I mostly reworded some of the comments to be clearer and used a single 'sudo' command with a here-document to reduce footprint. It's a small portion, I would imagine it will take a while to actually speed up the container but every little bit helps!

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

### CODE REVIEW

**Comment by JingyuMarcelLee** [comment]
Tested PR. Dev environment started without issues on WSL2 w/ Docker desktop.

**Comment by braughtg** [comment]
> Tested PR. Dev environment started without issues on WSL2 w/ Docker desktop.

Awesome - Thanks Marcel!

**Comment by braughtg** [comment]
Anyone else having a look at this PR you should:
- Fetch the PR
  - `git fetch origin pull/<ID>/head:<BRANCHNAME>`
  - `<ID>` is the number of the PR
  - `<BRANCHNAME>` is a name you give to the branch for the PR in your local repo.
- [Start FarmData2](https://github.com/DickinsonCollege/FarmData2/blob/main/INSTALL.md#starting-farmdata2)
- Confirm some basic functionality of the Dev Environment.
  - [Install the sample database](https://github.com/DickinsonCollege/FarmData2/blob/main/INSTALL.md#install-the-sample-database-image) 
  - [Open FarmData2](https://github.com/DickinsonCollege/FarmData2/blob/main/INSTALL.md#logging-into-farmdata2)
  - Create a seeding log and verify it exits
  - [Open VS Code](https://github.com/DickinsonCollege/FarmData2/blob/main/INSTALL.md#editing-code-and-documentation)
  - Run some tests
    - `./test_runner.bash ct` (Note: they may be out of date and not all may pass but Cypress should run).

**Review by braughtg — APPROVED** [review]
Looks good to me! Everything works well on Mac OS (M1)

**Review by JingyuMarcelLee — APPROVED** [review]

**Comment by FutzMonitor** [comment]
I will try to get to this review this weekend.

**Comment by FutzMonitor** [comment]
Everything is working well on my Windows 10 laptop using WSL2 with Docker Desktop.

**Comment by braughtg** [comment]
@

> Everything is working well on my Windows 10 laptop using WSL2 with Docker Desktop.

Please check of your approval of the PR on your review and I'll merge it.  Thanks!

**Review by FutzMonitor — APPROVED** [review]
Looking all good after testing it on my Windows 10 laptop using WSL2 and Docker desktop.

**Pull request merged**
