### PR TITLE
Issue-101: Updated instructions on install.md

### PR DESCRIPTION
**Pull request by Anisha-art**
Added the missing information as reported in issue:
https://github.com/DickinsonCollege/FarmData2/issues/101

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

### CODE REVIEW

**Comment by braughtg** [comment]
Very nice edits.  Were you able to complete a successful install on MacOS using the commands that you added?

**Comment by Anisha-art** [comment]
Hi,

Thanks for reviewing!
I use a windows laptop so I just followed the commands mentioned in the
issue details by the reporter. I couldn't verify them.

Thanks,
Anisha Chugh

**Comment by braughtg** [comment]
Thanks Aniasha.  Because the Mac steps are not verified, please update your PR to remove them.  Please retain the really good improvements you made on lines 79 and 93.  They definitely make things more clear.  Thanks.

**Comment by Anisha-art** [comment]
Removed the MacOS changes and retained the previous changes.

**Comment by braughtg** [comment]
Thank you for you help with FarmData!  It is most appreciated.  If you have an interest in getting deeper into FarmData, I suggest reviewing the CONTRIBUTING.md and the ONBOARDING.md files.  If you are new to web development, you might find the [FarmData2 School materials](https://github.com/DickinsonCollege/FarmData2/tree/main/farmdata2_modules/fd2_tabs/fd2_school) helpful as well.

**Pull request merged**
