### PR TITLE
Amelia - Harvest Report Field Selection

### PR DESCRIPTION
**Pull request by amelia291**
__Pull Request Description__

Issue #136  User Story: Field Selection
- Create the field selection
- Connect the field to API request and get back the data from the chosen field
- Show the harvest logs from the chosen field in a table

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

### CODE REVIEW

**Comment by braughtg** [comment]
I think this Pull Request (PR) is related to Issue #136 not Issue #137.  

Also, because your team is working on a single user story it would be preferable to have a single PR from your team that addresses the story.  Your team should merge your two branches into a single branch.  You can either merge the changes into the branch for this PR or into the branch for PR #142 that was submitted earlier.  Either way works.  Once you have done that please close the PR for the branch your team will not be using.

**Comment by braughtg** [comment]
If this story is complete and you believe it is ready for merging into main, click the "Ready for Review" button above to convert it from a draft pull request to a formal pull request. At which point it will be reviewed for merging. That review will result either in the changes being merged or additional feedback here to be addressed.

**Comment by braughtg** [comment]
How would you like to proceed with this?  I can:
1. Merge this before #142? 
2. Wait until #142 is merged and then merge this.
3. Have you merge this into #142 or vice versa and then consider merging that.

Let me know how you would like to proceed.

**Comment by amelia291** [comment]
This commit has already been merged with draft pull request #155.

**Pull request closed without merging**
