### PR TITLE
Total Yield and Crop Selection

### PR DESCRIPTION
**Pull request by Batese2001**
__Pull Request Description__

For Issue #136

This will add total yield to the Report.

It should:

- Compute the yield at the end of the report
- Use default harvest unit
- Separately add same crops together 

This will add crop selection to the Report.

It should:

- Add a crop dropdown
- Filter results by crop
- Ignore crop using ALL filter

This will add the basics of a Harvest Report generator to the Barn Kit tab.

It should:

- Generate a table using an button
- Get data from the database
- Have the ability to change the name of the Report
- Have instructions and a title for the tab

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

### CODE REVIEW

**Comment by braughtg** [comment]
Ideally all of the commits for a single story will be contained in a single pull request.  Try to  merge this branch into the one from the other open pull request that you have?  Or if this PR has all of the changes, then you can update the comments for this one and close the other.

**Comment by braughtg** [comment]
Please resolve the conflict in this PR by removing the conflicting file from the commits.  

Conflicting files
.theia/recentworkspace.json

That file has since been added to the .gitignore so once you remove it and synchronize with the upstream the issue should not repeat.

**Comment by braughtg** [comment]
If this story is complete and you believe it is ready for merging into main, click the "Ready for Review" button above to convert it from a draft pull request to a formal pull request.  At which point it will be reviewed for merging.  That review will result either in the changes being merged or additional feedback here to be addressed.

**Comment by Batese2001** [comment]
The total yield and crop selection branches have been merged and all changes (as well as fixes to make them work together) are contained here

**Comment by Batese2001** [comment]
The branches for Total Yield and Crop Selection have been merged here and this pull request contains them both, as well as some bug fixes to get them to work together

**Comment by braughtg** [comment]
This is looking good.  Please just convert the data from a timestamp to a date and then I can merge this into main.

**Comment by Batese2001** [comment]
This is redundant with the addition of pull request #155

**Pull request closed without merging**
