### PR TITLE
Create subtab story

### PR DESCRIPTION
**Pull request by IrisSC**
__Pull Request Description__

This story will add a new subtab for transplanting data. This subtab will be in the BarnKit tab. This story has a Vue.js and table included in the story. 

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

### CODE REVIEW

**Comment by braughtg** [comment]
The pull requests for the user stories to eventually be merged into the main branch should not include the any of the earlier spikes from A02-A06. Those were for practice and learning and will not become part of the final product.  So you'll need to remove all of those from your new feature branch.

**Comment by IrisSC** [comment]
> The pull requests for the user stories to eventually be merged into the main branch should not include the any of the earlier spikes from A02-A06. Those were for practice and learning and will not become part of the final product. So you'll need to remove all of those from your new feature branch.

I kept the example tabs because sometimes they can be helpful to look back at when writing new code or FarmData2. I can take them out at the end before making a pull request with the new changes back to DickinsonCollege/FarmData2. Do you have any suggests on how to be able to quickly look at some of that code from before without having it on the spike?

**Comment by braughtg** [comment]
> I kept the example tabs because sometimes they can be helpful to look back at when writing new code or FarmData2. I can take them out at the end before making a pull request with the new changes back to DickinsonCollege/FarmData2. Do you have any suggests on how to be able to quickly look at some of that code from before without having it on the spike?

You should still have the FarmData2 repo that you used for the spikes in a directory that is separate from the one that your team is using for implementing your stories.  The directory from your spikes will have all of the code that you wrote for those.  You can open those files in an editor (but not in Theia, because they will not be in the running docker container) and refer to them. So for example, you could use gedit or eclipse or atom or something like that to open your spike code.

**Comment by braughtg** [comment]
If this story is complete and you believe it is ready for merging into main, click the "Ready for Review" button above to convert it from a draft pull request to a formal pull request. At which point it will be reviewed for merging. That review will result either in the changes being merged or additional feedback here to be addressed.

**Comment by braughtg** [comment]
This appears to be already contained in PR #151.  So I am closing this PR and you should continue working on the branch for #151.  When that one gets to a functional point we will review and merge it.

**Pull request closed without merging**
