### PR TITLE
Barn Kit Tab Direct Seeding Report (issue 137)

### PR DESCRIPTION
**Pull request by brunokaboyi**
__Pull Request Description__

<Add description>
Label: Display seeding report for the selected crop, field, and date range in the Barn Kit Tab

Narrative: As a farmer, I would like to access the seeding report information so that I can analyze the results of direct seeding for each crop, field during the specified date range 

Acceptance Criteria: 
- The user can select specific crop, field, and dates (to and from) to filter reports
- Once a request with given information is sent, the table is displayed with information about each filtered report. The table contains information such as the date of seeding, field, rows/bed, row feet, hours, annual, comments, and user.
- The user can edit each seeding record modify any information as necessary 
- The user is able to delete any specific record 
- The summary for the total bed feet planted, total row feet planted, and total acres planted  is displayed at the bottom of the table 
- At the bottom of the page there is a button to run another report 
- At the bottom of the page there is a button to download the report

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

### CODE REVIEW

**Comment by braughtg** [comment]
Does the branch (issue137b) for this PR include all of the code that is also in #150?  If so, please close PR #150 and continue to work with this one.  If not, please merge the code from #150 into this branch and then close PR #150.  If you want to discuss please get in touch and we can work out the details.

**Comment by brunokaboyi** [comment]
> Does the branch (issue137b) for this PR include all of the code that is also in #150? If so, please close PR #150 and continue to work with this one. If not, please merge the code from #150 into this branch and then close PR #150. If you want to discuss please get in touch and we can work out the details.

The issue137b branch includes all the code that is also in #150. We will close PR #150, however, in the future, is it fine working on both branches and just merging this one (issue137b) into issue137?

**Comment by braughtg** [comment]
> The issue137b branch includes all the code that is also in #150. We will close PR #150, however, in the future, is it fine working on both branches and just merging this one (issue137b) into issue137?

If you want to use the branch issue137 instead of this one, then please merge this branch into that branch, close this PR and leave PR #150 open.  Then you can continue to merge all new changes into the issue137 branch and RP #150.

**Comment by braughtg** [comment]
Thanks for doing the merging and cleaning up the other pull request.  This PR now needs a good description of what its purpose is.  It should also have a good descriptive title.

**Comment by braughtg** [comment]
Merged by PR #163 that merged upstream changes.

**Pull request closed without merging**
