### PR TITLE
Add V1 to FarmOS API

### LINKED ISSUE #448: Links to FarmOS API Need to Point to v1
A number of links to the farmOS API (e.g. on CONTRIBUTING.md and ONBOARDING.md) point to the latest version of the farmOS API.  FarmData2 is currently using version 1 of the farmOS API and thus all links should point to that one.  The correct link appears in the FarmOS API section of the ONBOARDING.md file.   **All documentation should be searched for links to the new API and any found should be replaced with a link to the v1 API documentation.**

- Incorrect API link: https://farmos.org/development/api/
- Correct V1 API link: https://v1.farmos.org/development/api/

### PR DESCRIPTION
**Pull request by ezinneanne**
Added the V1 to the FarmOS API in CONTRIBUTING.MD and ONBOARDING.MD

Closes #448

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

### CODE REVIEW

**Comment by braughtg** [comment]
Thanks for your PR.  I think  that there may be another spot or two where the incorrect URL is used.  From a Linux command line you could find them all with the command: 

- `grep -r "https://farmos.org/development/api" .`

I suspect that the Mac searchlight would find any, and I'd imagine that there is a similar search feature in Windows or available via the Windows command line or also in the IDE you are using, if you are using one.

Can you please confirm that there are no more instances of the incorrect URL or correct any that you find and then add them to this PR?

**Comment by ezinneanne** [comment]
The 'grep -r' equivalent on my windows system is not functional.  I'm sorry I could not complete this as my system is not to par, could you unassign me please

**Comment by braughtg** [comment]
I ran the command above on my system and the relevant lines of output were:

```
farm@farmdata-VirtualBox:~/FarmData2$ grep -r "https://farmos.org/development/api" .

./ONBOARDING.md:Interacting with FarmData2 requires a basic familiarity with git and GitHub. 
FarmData2 development uses a fairly standard web technology stack including HTML, CSS, Bootstrap, 
JavaScript, and Vue.js. The front-end accesses FarmData2 data through the [FarmOS API]
(https://farmos.org/development/api/) using the [Axios](https://github.com/axios/axios) library. 
End-to-end testing is done using the [Cypress framework](https://www.cypress.io/). The automation, 
configuration and back-end development of FarmData2 use a number of other technologies including 
Drupal, drush, FarmOS, Docker, docker-compose and bash scripting.

./farmdata2_modules/fd2_tabs/fd2_example/api.html:  FarmData2 accesses, stores and manipulated its 
data through the farmOS system using its API.  
The farmdata2_modules/FarmData2/fd2_tabs/resources/FarmOSAPI.js 
file provide a library of JavaScript convenience functions for accessing the 
<a href='https://farmos.org/development/api/'>farmOS API</a>.

./CONTRIBUTING.md:Interacting with FarmData2 requires a basic familiarity with git and GitHub. 
FarmData2 development uses a fairly standard web technology stack including HTML, CSS, Bootstrap, 
JavaScript, and Vue.js. The front-end accesses FarmData2 data through the [FarmOS API]
(https://farmos.org/development/api/) using the [Axios](https://github.com/axios/axios) library. 
End-to-end and component testing is done using the [Cypress framework](https://www.cypress.io/).
```

So the link appears in 3 places and you already got two of them.  If you would like to fix the third and update your PR I'll be happy to merge it.  I will also unassign you if you prefer.  Just wanted to give you the change to finish this off since you got off to a good start on it.

**Comment by ezinneanne** [comment]
Thank you, I have updated it

**Comment by braughtg** [comment]
Thanks @ezinneanne.  We appreciate the help.  You are welcome to contribute any time!

**Pull request merged**
