### PR TITLE
Harvest Input Form Feature

### PR DESCRIPTION
**Pull request by goldberl**
__Pull Request Description__

- Adding a Harvest Input Form to the FieldKit subtab
- Addresses issue  #417 

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

### CODE REVIEW

**Comment by goldberl** [comment]
This should be a draft pull request (COMP 290)

**Comment by johnmaccormick** [comment]
would it be useful to update the PR description to state that this applies to [issue 417](https://github.com/DickinsonCollege/FarmData2/issues/417)?

**Comment by johnmaccormick** [comment]
It will be useful to note for future review purposes that this PR is based on work done in Prof John MacCormick's COMP 290 class at Dickinson College, Spring 2022.

**Comment by braughtg** [comment]
Closed as the course associated with this issue has concluded.  It will be preserved in the project history as a basis for implementation of this feature in the future.

**Pull request closed without merging**
